### ISSUE TITLE
TaintArt Deployment ，how to use addTaint and getTaint？

### ISSUE THREAD

**Issue by yongyecc** [mssun/taintart-art#2]
可以提供一下带有污点源和Sinks的framework源码吗，我想了解一下你提供的addTaint接口是如何使用的

**Comment by mxy2qk** [comment]
> 可以提供一下带有污点源和Sinks的framework源码吗，我想了解一下你提供的addTaint接口是如何使用的

你好，请问你了解他的污点存储设计主要是修改了哪些地方？(即寄存器机制和溢出机制的代码设计在哪个文件下)你还保留有测试app吗？我想了解以下你是如何调用接口的
